language: objective-c

osx_image: xcode8

cache:
  directories:
  - Carthage

env:
- DESTINATION="OS=10.1,name=iPhone 7" SCHEME="RxStateFlow" SDK=iphonesimulator10.1

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild clean build -project RxStateFlow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project RxStateFlow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
